package com.manueldidonna.pk.resources.text.english

import com.manueldidonna.pk.core.Version
import com.manueldidonna.pk.core.generation
import com.manueldidonna.pk.resources.text.PokemonTextResources

internal class EnglishMoves : PokemonTextResources.Moves {

    override fun getMoveById(id: Int): String {
        require(id in 0..251) { "id not supported: $id" }
        return if (id == 0) "" else moves[id]
    }

    override fun getAllMoves(version: Version): List<String> {
        return when (version.generation) {
            1 -> moves.subList(0, 166)
            2 -> moves
            else -> throw IllegalStateException("Unsupported version: $version")
        }
    }

    private val moves = listOf(
        "-------",
        "Pound",
        "Karate Chop",
        "Double Slap",
        "Comet Punch",
        "Mega Punch",
        "Pay Day",
        "Fire Punch",
        "Ice Punch",
        "Thunder Punch",
        "Scratch",
        "Vise Grip",
        "Guillotine",
        "Razor Wind",
        "Swords Dance",
        "Cut",
        "Gust",
        "Wing Attack",
        "Whirlwind",
        "Fly",
        "Bind",
        "Slam",
        "Vine Whip",
        "Stomp",
        "Double Kick",
        "Mega Kick",
        "Jump Kick",
        "Rolling Kick",
        "Sand Attack",
        "Headbutt",
        "Horn Attack",
        "Fury Attack",
        "Horn Drill",
        "Tackle",
        "Body Slam",
        "Wrap",
        "Take Down",
        "Thrash",
        "Double-Edge",
        "Tail Whip",
        "Poison Sting",
        "Twineedle",
        "Pin Missile",
        "Leer",
        "Bite",
        "Growl",
        "Roar",
        "Sing",
        "Supersonic",
        "Sonic Boom",
        "Disable",
        "Acid",
        "Ember",
        "Flamethrower",
        "Mist",
        "Water Gun",
        "Hydro Pump",
        "Surf",
        "Ice Beam",
        "Blizzard",
        "Psybeam",
        "Bubble Beam",
        "Aurora Beam",
        "Hyper Beam",
        "Peck",
        "Drill Peck",
        "Submission",
        "Low Kick",
        "Counter",
        "Seismic Toss",
        "Strength",
        "Absorb",
        "Mega Drain",
        "Leech Seed",
        "Growth",
        "Razor Leaf",
        "Solar Beam",
        "Poison Powder",
        "Stun Spore",
        "Sleep Powder",
        "Petal Dance",
        "String Shot",
        "Dragon Rage",
        "Fire Spin",
        "Thunder Shock",
        "Thunderbolt",
        "Thunder Wave",
        "Thunder",
        "Rock Throw",
        "Earthquake",
        "Fissure",
        "Dig",
        "Toxic",
        "Confusion",
        "Psychic",
        "Hypnosis",
        "Meditate",
        "Agility",
        "Quick Attack",
        "Rage",
        "Teleport",
        "Night Shade",
        "Mimic",
        "Screech",
        "Double Team",
        "Recover",
        "Harden",
        "Minimize",
        "Smokescreen",
        "Confuse Ray",
        "Withdraw",
        "Defense Curl",
        "Barrier",
        "Light Screen",
        "Haze",
        "Reflect",
        "Focus Energy",
        "Bide",
        "Metronome",
        "Mirror Move",
        "Self-Destruct",
        "Egg Bomb",
        "Lick",
        "Smog",
        "Sludge",
        "Bone Club",
        "Fire Blast",
        "Waterfall",
        "Clamp",
        "Swift",
        "Skull Bash",
        "Spike Cannon",
        "Constrict",
        "Amnesia",
        "Kinesis",
        "Soft-Boiled",
        "High Jump Kick",
        "Glare",
        "Dream Eater",
        "Poison Gas",
        "Barrage",
        "Leech Life",
        "Lovely Kiss",
        "Sky Attack",
        "Transform",
        "Bubble",
        "Dizzy Punch",
        "Spore",
        "Flash",
        "Psywave",
        "Splash",
        "Acid Armor",
        "Crabhammer",
        "Explosion",
        "Fury Swipes",
        "Bonemerang",
        "Rest",
        "Rock Slide",
        "Hyper Fang",
        "Sharpen",
        "Conversion",
        "Tri Attack",
        "Super Fang",
        "Slash",
        "Substitute",
        "Struggle",
        "Sketch",
        "Triple Kick",
        "Thief",
        "Spider Web",
        "Mind Reader",
        "Nightmare",
        "Flame Wheel",
        "Snore",
        "Curse",
        "Flail",
        "Conversion 2",
        "Aeroblast",
        "Cotton Spore",
        "Reversal",
        "Spite",
        "Powder Snow",
        "Protect",
        "Mach Punch",
        "Scary Face",
        "Feint Attack",
        "Sweet Kiss",
        "Belly Drum",
        "Sludge Bomb",
        "Mud-Slap",
        "Octazooka",
        "Spikes",
        "Zap Cannon",
        "Foresight",
        "Destiny Bond",
        "Perish Song",
        "Icy Wind",
        "Detect",
        "Bone Rush",
        "Lock-On",
        "Outrage",
        "Sandstorm",
        "Giga Drain",
        "Endure",
        "Charm",
        "Rollout",
        "False Swipe",
        "Swagger",
        "Milk Drink",
        "Spark",
        "Fury Cutter",
        "Steel Wing",
        "Mean Look",
        "Attract",
        "Sleep Talk",
        "Heal Bell",
        "Return",
        "Present",
        "Frustration",
        "Safeguard",
        "Pain Split",
        "Sacred Fire",
        "Magnitude",
        "Dynamic Punch",
        "Megahorn",
        "Dragon Breath",
        "Baton Pass",
        "Encore",
        "Pursuit",
        "Rapid Spin",
        "Sweet Scent",
        "Iron Tail",
        "Metal Claw",
        "Vital Throw",
        "Morning Sun",
        "Synthesis",
        "Moonlight",
        "Hidden Power",
        "Cross Chop",
        "Twister",
        "Rain Dance",
        "Sunny Day",
        "Crunch",
        "Mirror Coat",
        "Psych Up",
        "Extreme Speed",
        "Ancient Power",
        "Shadow Ball",
        "Future Sight",
        "Rock Smash",
        "Whirlpool",
        "Beat Up"
    )
}